#!/usr/bin/perl

# $Id: harness 26906 2008-04-10 19:45:40Z bernhard $

use FindBin;
use lib qw( . lib ../lib ../../lib ../../lib ../../../../lib );
use Parrot::Test::Harness language => 'c99', exec => [ '../../../../parrot', './', 'cpp.pbc' ] ;
